### ISSUE TITLE
Concept List generation script

### ISSUE THREAD

**Issue by lucifermorningstar1305** [artificial-scientist-lab/SciMuse#1]
Hi, 

Thanks for publishing and open-sourcing this amazing work. I am working on a similar kind of project and was wondering how did you generate the concept list. I was going through your paper but was unable to comprehend in detail the procedure involved in generating the concept lists. So, if possible can you guys please share the script for the concept list generation?

Cheers,
Adi

**Comment by jbdatascience** [comment]
> Hi,
> 
> Thanks for publishing and open-sourcing this amazing work. I am working on a similar kind of project and was wondering how did you generate the concept list. I was going through your paper but was unable to comprehend in detail the procedure involved in generating the concept lists. So, if possible can you guys please share the script for the concept list generation?
> 
> Cheers, Adi

Good question! I was wondering about this myself too!

I asked ChatGPT to answer this question based on the content of the pdf of the paper:


How are concepts extracted?

ANSWER:

Concepts are extracted for the knowledge graph using the following multi-step process:

1. Data Source
	•	Titles and abstracts from approximately 2.44 million papers were analyzed, including data from repositories like arXiv, bioRxiv, medRxiv, and chemRxiv.

2. Initial Extraction with RAKE
	•	The Rapid Automatic Keyword Extraction (RAKE) algorithm was applied to extract potential concepts.
	•	RAKE identifies phrases based on statistical co-occurrence and word frequency analysis.
	•	It focuses on multi-word expressions that frequently appear together in the text.

3. Filtering Rules
	•	Only certain phrases were retained based on criteria:
	•	Two-word concepts needed to appear in at least nine articles.
	•	Concepts with more than three words had to appear in at least six articles.
	•	This reduced the candidate list to 726,439 concepts.

4. Refinement and Error Removal
	•	Automated tools were developed to refine concepts and remove:
	•	Phrases that were not actual concepts (e.g., verbs or conjunctions).
	•	Domain-independent errors from RAKE’s output.
	•	This process resulted in a list of 368,825 refined concepts.

5. GPT and Manual Validation
	•	GPT-3.5 was used to review and remove irrelevant concepts further.
	•	Around 286,311 concepts were discarded at this stage.
	•	Wikipedia was utilized to restore 40,614 valid entries that were mistakenly removed.

6. Final Output
	•	The final list included 123,128 unique concepts.
	•	These concepts were from natural sciences, social sciences, and humanities, ensuring broad applicability.

This comprehensive process ensures that the extracted concepts are both meaningful and relevant for scientific research and knowledge graph construction.

**Comment by jbdatascience** [comment]
> Hi,
> 
> Thanks for publishing and open-sourcing this amazing work. I am working on a similar kind of project and was wondering how did you generate the concept list. I was going through your paper but was unable to comprehend in detail the procedure involved in generating the concept lists. So, if possible can you guys please share the script for the concept list generation?
> 
> Cheers, Adi

Describe in painstakingly detail the RAKE algorithm (Rapid Automatic Keyword Extraction )


The Rapid Automatic Keyword Extraction (RAKE) algorithm is a domain-independent method for extracting keywords or phrases from a text based on their statistical and positional properties. Below is a detailed explanation of the algorithm, step by step:

1. Input and Initialization

RAKE requires:
	•	A text document as input.
	•	A stop word list, which contains common words (e.g., “the”, “and”, “is”) that are not meaningful for keyword extraction.
	•	Optionally, a list of punctuation marks to identify boundaries in the text.

2. Text Preprocessing

RAKE preprocesses the text by:
	1.	Splitting the text into sentences using punctuation marks (e.g., “.”, “!”, “?”) as delimiters.
	•	Each sentence forms a unit for further processing.
	2.	Tokenizing sentences into words using spaces or other delimiters.

3. Stop Word Removal and Phrase Extraction
	1.	Words are classified as either stop words or candidate keywords:
	•	Stop words are identified using the predefined stop word list.
	•	Remaining words are treated as potential keywords.
	2.	Each sentence is divided into phrases:
	•	Stop words and punctuation act as boundaries, breaking the sentence into chunks.
	•	Example:
	•	Sentence: “AI models, such as GPT-4, are transformative.”
	•	Stop words: “such”, “as”, “are”.
	•	Phrases: “AI models”, “GPT-4”, “transformative”.
	3.	The resulting phrases consist of contiguous sequences of non-stop words.

4. Word Co-occurrence Matrix

RAKE builds a co-occurrence graph:
	1.	Each unique word from the extracted phrases is a node.
	2.	A co-occurrence link (or edge) is established between words that appear in the same phrase.
	•	Example:
	•	Phrases: [“AI models”, “GPT-4 transformative”]
	•	Co-occurrence pairs: (AI, models), (GPT-4, transformative).

5. Word Scoring

RAKE calculates two main metrics for each word:
	1.	Degree (d(w)):
	•	The number of other words it co-occurs with (i.e., the number of edges connected to the word in the co-occurrence graph).
	•	Example:
	•	“AI” in the phrase “AI models” has a degree of 1 (it co-occurs with “models”).
	2.	Frequency (f(w)):
	•	The number of times the word appears in the entire text.
	3.	Degree-to-Frequency Ratio (d(w) / f(w)):
	•	This ratio highlights words that are strongly connected to others but not overly frequent, balancing specificity and importance.

6. Phrase Scoring

For each candidate phrase:
	1.	Compute the score of the phrase by summing the scores of all words in the phrase.
	•	Example:
	•	Phrase: “AI models”.
	•	Word scores:  \text{Score(AI)} + \text{Score(models)} .
	•	Phrase score =  (\frac{d(\text{AI})}{f(\text{AI})}) + (\frac{d(\text{models})}{f(\text{models})}) .
	2.	Phrases with higher scores are ranked as more significant.

7. Output

RAKE outputs:
	•	A ranked list of phrases, where higher-ranked phrases are considered more important keywords for the text.

Advantages of RAKE
	1.	Domain Independence: It does not rely on pre-trained models or domain-specific knowledge.
	2.	Simplicity: The algorithm is computationally efficient and easy to implement.
	3.	Customizability: The stop word list can be tailored to suit specific domains or languages.
	4.	Phrase-Based: Unlike single-word extraction methods, RAKE identifies meaningful multi-word phrases.

Example Walkthrough

Input Text:

“Artificial intelligence models like GPT-4 are transformative tools in research.”

Step-by-Step Process:
	1.	Split into Sentences:
	•	Sentence: “Artificial intelligence models like GPT-4 are transformative tools in research.”
	2.	Tokenize and Remove Stop Words:
	•	Stop words: “like”, “are”, “in”.
	•	Result: [“Artificial intelligence models”, “GPT-4”, “transformative tools”, “research”].
	3.	Extract Co-occurrence Pairs:
	•	Phrases: [“Artificial intelligence models”, “GPT-4”, “transformative tools”, “research”].
	•	Co-occurrence pairs:
	•	From “Artificial intelligence models”: (Artificial, intelligence), (Artificial, models), (intelligence, models).
	•	From “transformative tools”: (transformative, tools).
	4.	Calculate Word Scores:
	•	Degree (d):
	•	“Artificial” = 2, “intelligence” = 2, “models” = 2, etc.
	•	Frequency (f):
	•	“Artificial” = 1, “intelligence” = 1, etc.
	•	d / f:
	•	“Artificial” = 2, “intelligence” = 2, etc.
	5.	Score Phrases:
	•	Phrase “Artificial intelligence models” = 2 + 2 + 2 = 6.
	•	Phrase “transformative tools” = 2 + 2 = 4.
	6.	Rank and Output:
	•	Ranked Phrases:
	1.	“Artificial intelligence models” (Score: 6).
	2.	“transformative tools” (Score: 4).
	3.	“GPT-4” (Score: 2).

Applications

RAKE is used in:
	1.	Summarization of documents.
	2.	Topic modeling and content analysis.
	3.	Preprocessing for machine learning pipelines in NLP tasks.

**Comment by lucifermorningstar1305** [comment]
> > Hi,
> > 
> > Thanks for publishing and open-sourcing this amazing work. I am working on a similar kind of project and was wondering how did you generate the concept list. I was going through your paper but was unable to comprehend in detail the procedure involved in generating the concept lists. So, if possible can you guys please share the script for the concept list generation?
> > 
> > Cheers, Adi
> 
> Good question! I was wondering about this myself too!
> 
> I asked ChatGPT to answer this question based on the content of the pdf of the paper:
> 
> 
> How are concepts extracted?
> 
> ANSWER:
> 
> Concepts are extracted for the knowledge graph using the following multi-step process:
> 
> 1. Data Source
> 	•	Titles and abstracts from approximately 2.44 million papers were analyzed, including data from repositories like arXiv, bioRxiv, medRxiv, and chemRxiv.
> 
> 2. Initial Extraction with RAKE
> 	•	The Rapid Automatic Keyword Extraction (RAKE) algorithm was applied to extract potential concepts.
> 	•	RAKE identifies phrases based on statistical co-occurrence and word frequency analysis.
> 	•	It focuses on multi-word expressions that frequently appear together in the text.
> 
> 3. Filtering Rules
> 	•	Only certain phrases were retained based on criteria:
> 	•	Two-word concepts needed to appear in at least nine articles.
> 	•	Concepts with more than three words had to appear in at least six articles.
> 	•	This reduced the candidate list to 726,439 concepts.
> 
> 4. Refinement and Error Removal
> 	•	Automated tools were developed to refine concepts and remove:
> 	•	Phrases that were not actual concepts (e.g., verbs or conjunctions).
> 	•	Domain-independent errors from RAKE’s output.
> 	•	This process resulted in a list of 368,825 refined concepts.
> 
> 5. GPT and Manual Validation
> 	•	GPT-3.5 was used to review and remove irrelevant concepts further.
> 	•	Around 286,311 concepts were discarded at this stage.
> 	•	Wikipedia was utilized to restore 40,614 valid entries that were mistakenly removed.
> 
> 6. Final Output
> 	•	The final list included 123,128 unique concepts.
> 	•	These concepts were from natural sciences, social sciences, and humanities, ensuring broad applicability.
> 
> This comprehensive process ensures that the extracted concepts are both meaningful and relevant for scientific research and knowledge graph construction.
> 
> 

Hi,

Thanks for your response. I emailed the author a month ago, and she shared me the link for the code. Here's the link, if you are interested:

https://github.com/artificial-scientist-lab/Impact4Cast/tree/main/create_concepts

Cheers,
Adi

**Comment by XuemeiGu** [comment]
Hi Jan and Adi,

Thank you for reaching out! Apologies for missing the earlier message. Here's an overview of our approach to concept extraction:

1. Initial Concept Extraction:
We analyzed the titles and abstracts of approximately 2.44 million papers from four preprint datasets using the RAKE algorithm, enhanced with additional stopwords, to extract potential concept candidates.
- Initial filtering retained two-word concepts appearing in at least nine articles.
- Concepts with more than three words were retained if they appeared in six or more articles.
This process significantly reduced the concept list.
 

2. Quality Improvement:
To enhance the quality of identified concepts, we implemented a suite of automated tools to address domain-independent errors commonly associated with RAKE. We then manually reviewed and removed inaccuracies such as non-conceptual phrases, verbs, and conjunctions. For further details, refer to the [Impact4Cast Paper](https://arxiv.org/abs/2402.08640) and our [GitHub code for concept extraction](https://github.com/artificial-scientist-lab/Impact4Cast/tree/main/create_concepts).
 

3. Further Refinement with GPT:
We used GPT-3.5 to refine the concepts further, which resulted in the removal of 286,311 entries. Using Wikipedia, we restored 40,614 mistakenly removed entries, resulting in a final, refined list of 123,128 concepts. For details on prompt engineering, refer to the appendix of the [SciMuse paper](https://arxiv.org/abs/2405.17044).

You can find the code for generating and refining concepts in this repository:
[GitHub - Impact4Cast Concept Extraction](https://github.com/artificial-scientist-lab/Impact4Cast/tree/main/create_concepts).

Please let me know if there’s anything else you’d like to discuss!
